### ISSUE TITLE
Move GO Google drive to a shared drive

### ISSUE THREAD

**Issue by kltm** [geneontology/project-management#12]
##### Project link
https://github.com/orgs/geneontology/projects/90

##### Project description
Migrate all of our files and users from the old shared Google Drive to the new Org-based Google Drive.

##### PI
Chris

##### Project owner (PO)
Suzi

##### Technical lead (TL)
Seth

##### Other personnel (OP)
All managers.

##### Technical specs
No software necessary.

##### Other comments
Organizing ticket : https://github.com/geneontology/go-site/issues/1813

**Comment by suzialeksander** [comment]
https://github.com/geneontology/go-site/issues/1813 was closed, and after a final check I believe this project is complete.  

Do we need to 'delete' the old drive, or are the permission restrictions sufficient?

**Comment by kltm** [comment]
I think the restrictions are fine. I'm not 100% sure what delete means in this case anyways.
