### ISSUE TITLE
GO API refactor

### ISSUE THREAD

**Issue by kltm** [geneontology/project-management#14]
##### Project link
https://github.com/orgs/geneontology/projects/126

##### Project description
This project is the first in a series of stages we wish to accomplish for our strategic API goals.

This first stage is meant to clean up and restabilize previous work done on the GO API.
The completion of this first stage is when we have a refactored GO API in production that is: independent of AWS services, reproducible and easily deployable, documented, has tests, has excess and legacy code removed, and exists in a modern python environment. This includes some devops.

As well, as part of this process, we are merging in (the surprisingly simple) GO-CAM API and doing a survey of our traffic to make sure that the only generally used endpoints are: the GO API, SPARQL (if necessary), GOlr (for AmiGO and Noctua only).

##### PI
Chris

##### Project owner (PO)
Chris

##### Technical lead (TL)
Seth

##### Other personnel (OP)
Sierra, Patrick, Dustin, Tremayne

##### Technical specs
Tech doc: https://docs.google.com/document/d/10hU90xYuLmPU6srWPuPZa8i-RwcyaZjyAQNSUvFAKEk/edit#heading=h.ok1s2j4w41vo

##### Other comments
N/A

**Comment by pgaudet** [comment]
Managers call: 
The remaining work should be done by the end of 2022 if Sierra can continue at 20% 
+ Seth ; no other significant resources needed

**Comment by kltm** [comment]
Noting for @pgaudet: we tried to "upgrade" the project from "classic" to the new project format, but it unfortunately seems to have been a copy/close, rather than an actual upgrade. This means that upgrading projects breaks our links. Good to know.
Was: https://github.com/orgs/geneontology/projects/85 , now https://github.com/orgs/geneontology/projects/126

**Comment by kltm** [comment]
Due to the speed and nature of the progress in this project, we have merged in #54 and #2 and closed them out.
@sierra-moxon Let's touch bases soon to make sure this merged state makes sense.
Tagging @pgaudet .

**Comment by cmungall** [comment]
What's the current status of this @kltm?

**Comment by kltm** [comment]
Hm. I would want to touch bases with @sierra-moxon when she gets back, but I think it might be useful to split this into two aspects for the remaining parts: getting off of the old platform (in progress with @sierra-moxon @abessiari, currently looking at some HTTPS-related issues with the new rollout) and improvements to the combined API to reach specific goals (i.e. making sure that traffic is going where we want and we are not getting overloaded).

The initial parts, such as the python-ification and being standalone are pretty much complete. I believe that some of the items there in the TODO section of the project may be complete or have significant progress on them, but have not moved in the metadata for some reason (would want to check with @sierra-moxon ).

After that, as the devops portion is basically complete, I'd think a wrap-up session would be good and then fold any remaining items into future projects (further refactor or GO-CAM API extension) if there is anything outstanding that we still want.

**Comment by sierra-moxon** [comment]
I’ll take a look through the tickets here and close if needed/etc.  I haven’t done that in awhile.

**Comment by cmungall** [comment]
@kltm Let's make sure that the summaries here are consistent with the remaining open issues in the project!

**Comment by sierra-moxon** [comment]
I went ahead and added my summary for 2 to a new ticket here: (https://github.com/orgs/geneontology/projects/126?pane=issue&itemId=34283163), and added 1 to this existing ticket: https://github.com/orgs/geneontology/projects/126/views/1?pane=issue&itemId=34282472

sorry about that.

**Comment by kltm** [comment]
> @kltm Let's make sure that the summaries here are consistent with the remaining open issues in the project!

@cmungall Which summaries do you mean? I think my summary at https://github.com/geneontology/project-management/issues/14#issuecomment-1650436581 was correct, and there was an elaboration from @sierra-moxon ? I believe the state of the tickets is consistent with what is noted here now.

**Comment by pgaudet** [comment]
@sierra-moxon needs to write the documentation 
She will be available to do this next week possibly?

**Comment by kltm** [comment]
Production test underway as of this afternoon.

**Comment by kltm** [comment]
The documentation still needs work. A little awkward maybe, but we now https://github.com/geneontology/go-fastapi/issues/78 in the "software/proactive/bugs" and on the agenda for an upcoming software call, so we are good to close this out.
