### ISSUE TITLE
Visual Pathway Editor

### ISSUE THREAD

**Issue by kltm** [geneontology/project-management#15]
##### Project link
https://github.com/orgs/geneontology/projects/84

##### Project description
Lorem ipsum

##### PI
PaulT

##### Project owner (PO)
PaulT

##### Technical lead (TL)
TBD

##### Other personnel (OP)
Tremayne

##### Technical specs
https://docs.google.com/document/d/18QNkLheCOoWSEso_T1-DSJZsjJH266WfA8bk1cP10a8/edit

##### Other comments

Home repo: https://github.com/geneontology/visual-pathway-editor

Paul's original user stories: https://docs.google.com/document/d/1-G4i6bdcpzMsDCFW_ntrAJjbpiCUMuPsZi9lIKtiwuY/edit

**Comment by kltm** [comment]
@pgaudet Not sure how much to revisit here as it's already active.

**Comment by pgaudet** [comment]
All tickets in the project are closed, so we can close the project - 

However Tremayne implemented ['adding a comment' ](https://github.com/geneontology/noctua-visual-pathway-editor/issues/43) on dev; could this be pushed to prod?
