### ISSUE TITLE
GO-CAM browser / site migration

### ISSUE THREAD

**Issue by kltm** [geneontology/project-management#18]
##### Project link
https://github.com/orgs/geneontology/projects/70

##### Project description

The purpose of this project is restore the initial functionality of the site, ie. show connected models

Later - possibly in a separate project, we would like to:

1. create a portable web component based version of the GO-CAM browser (geneontology.cloud)
2. put this into production on the usual GH pages GO site, replacing (and removing) geneontology.cloud

##### PI
TBD

##### Project owner (PO)
TBD

##### Technical lead (TL)
TBD

##### Other personnel (OP)
TBD

##### Technical specs
https://docs.google.com/document/d/1hnsgrasQr6G311MiMtoSiveSt14QrEZONu62nsnu25U/edit

##### Other comments
N/A

**Comment by pgaudet** [comment]
The fix that was done, ie to filter the models that contain at lest 3 connected units in the display, fixes the immediate problem. There is a new project for the next work on the GO-CAM browser (https://github.com/orgs/geneontology/projects/55) - Chris and Paul will update the specs document.

**Comment by kltm** [comment]
Fix was done, essentially as a bugfix. Will either spin up new projects or move issues to appropriate location.
