### ISSUE TITLE
Provide GORULE reports by "assigned by"

### ISSUE THREAD

**Issue by pgaudet** [geneontology/project-management#23]
##### Project link
https://github.com/orgs/geneontology/projects/121

##### Project description
Contributing groups would like to have a report with *only* the annotations they have made, in addition to the current report on the file they submit.

##### PI
Chris

##### Project owner (PO)
Pascale

##### Technical lead (TL)
Dustin

##### Other personnel (OP)
Anushya (who will complete the main work)

##### Technical specs
https://docs.google.com/document/d/12C10hrgepykJSbhfsLikRbf_tHzDK_Rq4EoVj550P3c/edit#

##### Other comments
Also see (but not in scope) related ([Split reports by database](https://github.com/geneontology/shared-annotation-check/issues/2))

**Comment by kltm** [comment]
@pgaudet Removed 
```
Two parts: 
1. Filter the current report for 'Assigned by' that do not correspond to the group
2. Add annotations 'Assigned by' the source from other reports
Alternatively, all reports could be merged into a single report and the report be parsed for source.
```
as part of technical discussion; see tickets and project.

**Comment by kltm** [comment]
Noting that this seems to be regenerating right now and should be complete again in eight hours.

**Comment by mugitty** [comment]
@pgaudet, we can have curators QC the data

'groups' data comes from the "assigned-by" field in the GAF line.  If the GAF line does not have the 'assigned-by' field or the number of items in the GAF line is invalid, then the source of the GAF line is used.

Once you are satisfied with the output, we can make it part of the pipeline output.

The old output(http://skyhook.berkeleybop.org/issue-go-site-1944-assigned-by-reports/reports/gorule-report.html), it is still accessible

**Comment by vanaukenk** [comment]
From 2023-02-21 annotation conference call:

Can we get the full report for all Assigned_by groups?

That will help groups QC their data.

Some that are missing: FlyBase, TAIR, ZFIN

**Comment by pgaudet** [comment]
@mugitty We will wait for the complete report to be ran before asking groups for feedback. 

Thanks, Pascale

**Comment by mugitty** [comment]
@pgaudet, the complete report is available on http://skyhook.berkeleybop.org/issue-go-site-1944-assigned-by-reports/reports/gorule-report.html

**Comment by pgaudet** [comment]
Status: waiting for a test release to be successful
