### ISSUE TITLE
GPAD/GPI 2.0 Specifications

### ISSUE THREAD

**Issue by pgaudet** [geneontology/project-management#26]
##### Project link
https://github.com/orgs/geneontology/projects/35

##### Project description
Lorem ipsum

##### PI
Chris

##### Project owner (PO)
@suzialeksander 

##### Technical lead (TL)
@kltm 

##### Other personnel (OP)
TBD

##### Technical specs
TBD

##### Other comments
- Grant Aim #: 2 Annotation and 4 Software Infrastructure
- Priority: High

**Comment by kltm** [comment]
Initial feedback from @balhoff 
```
 I think there are still a few grammar issues—this is still applicable: https://github.com/geneontology/go-annotation/issues/3648

We have these property names with hyphens, but that’s disallowed by the grammar.

We could consider pointing to https://www.w3.org/TR/curie/ instead of defining our own ID.

Not sure if Property_Symbol should include ID; I think all the examples are hyphenated terms.

‘Value' in GPAD header line is not defined.
```

**Comment by pgaudet** [comment]
Once this is out, we'll make a new project for GOC to start exporting GPAD/GPI2.0

**Comment by kltm** [comment]
@pgaudet I'm not sure if a "new" project is necessarily the best way forward on this. It's worth considering that emitting the final GPAD 2.0 spec will be a necessary condition for the completion of the MGI project #77 . Other things may come into line with the spec at different speeds.

**Comment by pgaudet** [comment]
@kltm 

Some bugs in the pipeline that prevented production of GPAD2.0

Potentially fixed, to be confirmed.

**Comment by kltm** [comment]
@pgaudet This project seems to be about "specs" and is functionally done, as the only remaining bits are docs?

**Comment by pgaudet** [comment]
Right now the documentation is not linked from the GO website 
I thought you wanted the GO pipeline to produce the GPAD2.0 files  before doing that. 

This is the last task needed.

**Comment by kltm** [comment]
Ah, natch--right you are!

**Comment by kltm** [comment]
@pgaudet As discussed, remaining (coordination) items moved out and closing.
