### ISSUE TITLE
Pipeline cleanup

### ISSUE THREAD

**Issue by pgaudet** [geneontology/project-management#32]
##### Project link
https://github.com/orgs/geneontology/projects/86

##### Project description
Clean up and simplify some expensive and rough edges in the pipeline.
Specified as the tickets in the project.

##### PI
@cmungall 

##### Project owner (PO)
@pgaudet 

##### Technical lead (TL)
@kltm 

##### Other personnel (OP)
@dustine32 @sierra-moxon 

##### Technical specs
[Pipeline cleanup tech specs](https://docs.google.com/document/d/1gkEPsL3Fg-aSCxwClyuSPvp_x2SdpF_YnPfCKly1CEY/edit#heading=h.ok1s2j4w41vo)

##### Other comments
N/A

**Comment by pgaudet** [comment]
Managers call update: 
- in progress 
- https://github.com/geneontology/pipeline/issues/268
- https://github.com/geneontology/pipeline/issues/269

Do we want to do more of these tickets? or close the project for now.

**Comment by kltm** [comment]
From discussion with @pgaudet reducing scope of project slightly, moving some items into other projects (in "To do").

**Comment by kltm** [comment]
@pgaudet This project is essentially "on hold" until the next release when we can check the final change and update the documentation.

**Comment by pgaudet** [comment]
OK, I moved it back into "Resourcing"

**Comment by pgaudet** [comment]
All tickets should be done after the next release (hopefully)

**Comment by kltm** [comment]
@pgaudet Should be wrapped up now. Please reopen if I missed anything.
