### ISSUE TITLE
Refactor GO_REF deployment

### ISSUE THREAD

**Issue by pgaudet** [geneontology/project-management#33]
##### Project link
https://github.com/orgs/geneontology/projects/88

##### Project description

The purpose of this project is to refactor the GO_REFs file so that it is generated from a schema-controlled (LinkML) YAML file, which then generates and publishes to an updated (PURL) location.

##### PI

Chris

##### Project owner (PO)

Pascale

##### Technical lead (TL)

Seth

##### Other personnel (OP)

Patrick; Seth

##### Technical specs

Covered in previous iteration and tickets
~[GO_REF deployment tech specs](https://docs.google.com/document/d/1VcB5xOTc5UuVcBWiu1eomBG_0DZ7J-8Io-Eb0FeGIzA/edit#heading=h.cmbmy6wzbdsg)~

##### Other comments
N/A

**Comment by kltm** [comment]
Going to say this is fine for the moment, as we're going to attempt to fly through this.

**Comment by kltm** [comment]
@pgaudet , @sierra-moxon may have time for this.

**Comment by kltm** [comment]
Talking to @pgaudet, this is ready again and waiting for resources ("Resourcing").

**Comment by kltm** [comment]
Making sure that @pkalita-lbl is tagged on.

**Comment by kltm** [comment]
@pgaudet The project issues have been refreshed after a review with @pkalita-lbl, who put together a new (and very nice) plan. The remaining item is to work out _grossly_ how long this might take. @pkalita-lbl, feel free to give any thoughts here, otherwise I'll chat with you on slack or somewhere and we can think it through.

**Comment by pgaudet** [comment]
Looks good. I commented on the implementation plan, @pkalita-lbl if you could have a look and reply to my questions that'd be great. 

Pascale

**Comment by pkalita-lbl** [comment]
@pgaudet I think I got to all of your questions. If I missed something or you need more details please let me know.

@kltm Given my current time allocation I could see picking off about one issue in this project per week. That would wrap up all the work around mid-April.

**Comment by kltm** [comment]
@pgaudet, @pkalita-lbl is getting close; we now have a functional and automated location at https://geneontology.org/gorefs .

With that, I wanted to know if you had any feedback on the URLs. Naturally, the official PURLs will be clean (https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/go.yml#L76-L80), but for day to day use (bookmarks), you may want something that fits our normal usage.

So, we currently would have `https://geneontology.org/gorefs/go_ref0000051.html`. I wanted to make sure that `go_ref` was preferred over other variants that I've seen, like `goref` and `GO_REF`. As well, for the numbering, would a dash be preferred there, to match our old metadata?

**Comment by pgaudet** [comment]
Do we have a list of our PURLs somewhere? It would be good to standardize this. 
Right now the official prefix is "GO_REF:", I find it confusing to vary in different contexts.

**Comment by kltm** [comment]
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/go.yml

**Comment by kltm** [comment]
@pkalita-lbl Talking to @pgaudet here, this is the preference moving forward (although a little more work):

I believe that URLs resolve without the `.html`, so the "preferred" final right now would be, for example:

https://geneontology.org/GO_REF/0000051

(which may practically resolve to https://geneontology.org/GO_REF/0000051.html, depending).

I know that it may be a little quirky to have those in the top level, but I believe that works if you have an alternate URL in place? Having the /gorefs.html index would remain as-is; only the reference page, looking a bit like an object that closely matches the CURIE, would change.

I just tried looking at the plumbing right now, but was a little unsure if this was a reasonable ask. Let me know if it seems odd or fiddly and we can iterate on it. The main target is to get the individual pages looking as close to looking as close to the CURIE under our TLD as we _reasonably_ can.

**Comment by pkalita-lbl** [comment]
I think that's reasonable. Or, at least, let's assume it is until I learn otherwise 😁

**Comment by pkalita-lbl** [comment]
The URL update is now complete via https://github.com/geneontology/geneontology.github.io/pull/534.

- The index page is still at https://geneontology.org/gorefs
- Individual ref pages are at, for example, https://geneontology.org/GO_REF/0000051

The URLs should resolve with or without a `.html` extension.

With that I assume we're now ready to work on updating the OBO PURLs to point to the new individual ref pages (https://github.com/geneontology/go-site/issues/2236)?

**Comment by kltm** [comment]
@pkalita-lbl Yes, I believe so. If the new pages are in play, we should just go ahead and updated--right now, they don't seem to be working so well, so there is nothing lost in moving forward.

**Comment by kltm** [comment]
@pgaudet (@pkalita-lbl) All items in this project are now closed. If there are any loose ends (release notes later, announcements, etc.), we can add tickets. Otherwise, this and the kanban board can be closed.
