### ISSUE TITLE
Loading ibeetle base

### ISSUE THREAD

**Issue by pgaudet** [geneontology/project-management#43]
##### Project link
https://github.com/orgs/geneontology/projects/110

##### Project description
It looks like iBeetleBase, who we talked to earlier in the year, have made a one-off set of annotations and have modified these as we'd asked.  
Plan is to have GOA load the data and GOC load this as Uniprot-other

##### PI
TBD

##### Project owner (PO)
@suzialeksander 

##### Technical lead (TL)
NA - This is currently planned to go via the GOA pipeline

##### Other personnel (OP)
@pgaudet, @kltm 

##### Technical specs
Only possible modifications to metadata

##### Other comments
N/A

**Comment by kltm** [comment]
@suzialeksander I'd like to sign off on the technical aspect of this project--is there anything that needs to be done on the GO side of the fence?

**Comment by suzialeksander** [comment]
At this point, I don't think there's any super technical work. Alex will be loading these through P2GO.

However, the group might need an entry in groups.yaml correct? I don't see them there but can add it- the parent group is GOC not GOA correct @pgaudet ?

**Comment by pgaudet** [comment]
Looks good, thanks !

**Comment by suzialeksander** [comment]
They're live on QuickGO. UniProt release may be tomorrow, but if not they'll be there in the next 8 week cycle.
