### ISSUE TITLE
Noctua-Form ticket prioritization

### ISSUE THREAD

**Issue by ukemi** [geneontology/project-management#44]
##### Project link
https://github.com/orgs/geneontology/projects/112

##### Project description
This project is intended to prioritize issues in the Noctua Form Repository for curators who are using the form regularly. The order of prioritization will be order of appearance in the ticket list in the project. Once the tickets are prioritized, they will be migrated to a new project in which they will be addressed.

##### PI
PaulT

##### Project owner (PO)
David

##### Technical lead (TL)
NA

##### Other personnel (OP)
MGI curators

##### Technical specs
N/A

##### Other comments
N/A

**Comment by pgaudet** [comment]
This project is intended to prioritize issues in the Noctua Form Repository  - no tech doc required yet

**Comment by pgaudet** [comment]
The project metadata in which these improvements will be implemented is here: 
https://github.com/geneontology/project-management/issues/45
