### ISSUE TITLE
Ensure that the Noctua stack receives no external traffic

### ISSUE THREAD

**Issue by kltm** [geneontology/project-management#54]
##### Project link
https://github.com/orgs/geneontology/projects/116

##### Project description

The purpose of this project is to ensure that no public traffic is linked to or uses the noctua stack except for the direct purpose of curation.

The point of this project is prevent non-curation traffic from interfering with normal operations. As a demonstration of the issue, we have previously dealt with outages caused by spiders crawling third-party sites (alliance) triggering API calls into our curation system at such a high volume that it was brought down. While this has been temporarily mitigated, there are other ways into the system. For example:

* Currently, GO-CAM URIs resolve to the graph editor; we know of groups that use these as links for their work
* Links from widgets that we produce lead back to a view that is drive by the curation system

The most robust solution would be to public facing replacement for these views that does not depend on the curation system (e.g. the /go-cam site or a new TBD site); all links and URIs should resolve to there.

##### PI
Chris

##### Product owner (PO)
Suzi

##### Technical lead (TL)
Seth

##### Other personnel (OP)
Tremayne (; possibly Dustin)

##### Technical specs
TBD

##### Other comments
At least part of this would involve https://github.com/geneontology/api-gorest-2021/issues/6

**Comment by pgaudet** [comment]
In terms of resources (Seth), this may need to be done after the [pipeline cleanup](https://github.com/geneontology/project-management/issues/32) is done , or more advanced

**Comment by kltm** [comment]
From discussion last week, we think that it may be possible to give a more permanent home to GO-CAM URIs within AmiGO, using the JSON blobs to drive a widget--this would be relatively easy. @kltm to more fully spec out this work after reviewing some AmiGO internals. As no new load needs to be created, this should be a small to small-medium task.

**Comment by kltm** [comment]
Taking over:  Prevent non-curation traffic from accessing the curation system (Noctua) #49

**Comment by kltm** [comment]
@pgaudet From my email, this is being merged with https://github.com/geneontology/project-management/issues/14 as the GO API and GO-CAM APIs are already getting merged. Note to @sierra-moxon .
