### ISSUE TITLE
GO-CAM Enrichment - research project Paul S lab

### ISSUE THREAD

**Issue by kltm** [geneontology/project-management#6]
##### Project link
https://github.com/orgs/geneontology/projects/101

##### Project description
This project tracks the tasks needed to explore GO-CAM enrichment with PaulS's summer student Nick.

PI: Chris (PaulS) PO: Kimberly TL: Dustin Other: Kimberly, Jim, Dustin

##### PI
Chris; PaulS

##### Project owner (PO)
Kimberly

##### Technical lead (TL)
Dustin

##### Other personnel (OP)
Jim

##### Technical specs

None needed, as no software will be written by "core GO" people.

##### Other comments

Dustin, as "TL", is acting as liaison and helping, not writing software.

**Comment by kltm** [comment]
@pgaudet Is this a GO-managed project?

**Comment by pgaudet** [comment]
I think @vanauken and @dustine32 contribute to this, so I think it is.

**Comment by kltm** [comment]
@pgaudet Okay, great. Does this require any technical resources then. My understanding is that, while this has a GO-managed aspect, the technical aspects are entirely outside GO-management?

**Comment by pgaudet** [comment]
Probably not a GO project. We will follow up with Dustin to see how much time he needs for this work.

**Comment by pgaudet** [comment]
Paper has been submitted
