### ISSUE TITLE
Model copy with evidence

### ISSUE THREAD

**Issue by pgaudet** [geneontology/project-management#60]
##### Project link
https://github.com/orgs/geneontology/projects/133

##### Project description
Model copy with the option of copying the evidence (ECO + reference, and 'with', if applicable) 

##### PI
Paul

##### Product owner (PO)
Kimberly

##### Technical lead (TL)
Jim

##### Other personnel (OP)
David, Tremayne

##### Technical specs
https://docs.google.com/document/d/1EwsFJULezTgHNwT5v63u1NiOKGonToLNCHVlOwp3r2s/edit#heading=h.5gbed1nq2dbc

##### Other comments
N/A

**Comment by kltm** [comment]
Briefly talking to @balhoff on the software technical call, depending on the required fields and filters, this will likely be a "simple" addition if we follow the work that was done for the previous copy implementation.

**Comment by kltm** [comment]
Talking with @vanaukenk and @balhoff , this extends current work--nothing novel to worry about.

**Comment by pgaudet** [comment]
Tested showed no error - this is added to the Noctua outage tasks tomorrow May 25th.
