### ISSUE TITLE
Relations to link MF to BP in GO-CAMs and annotations

### ISSUE THREAD

**Issue by pgaudet** [geneontology/project-management#63]
##### Project link
https://github.com/orgs/geneontology/projects/130

##### Project description
Continuing the work on https://github.com/geneontology/project-management/issues/7 where relations to link MF to MF were refined and usage was documented. This project will document usage of MF to BP relations, including examples, and update RO if needed. 

##### PI
Paul

##### Product owner (PO)
Kimberly

##### Technical lead (TL)
NA

##### Other personnel (OP)
David, Jim, Pascale

##### Technical specs
TBD (template: https://docs.google.com/document/d/111UqtS3G0aJZpAijZYI3Da0t94OQpGePlPJsqZE4Tio/edit)

##### Other comments
N/A

**Comment by vanaukenk** [comment]
- [ ] Review SheX for MF shape
- [ ] Document MF to BP for GO-CAMs (causal models)
- [ ] Document MF to BP for other Noctua curation
- [ ] Update Protein2GO to reflect current guidelines

**Comment by kltm** [comment]
@vanaukenk Just to confirm: there is no TL or technical doc needed here, right?

**Comment by pgaudet** [comment]
GORELs left in Noctua graph: are these being used? 
results_in   (obo:GOREL_0000040)
results_in_division_of   (obo:GOREL_0001019)
results in distribution of   (obo:GOREL_0002003)
results_in_fission_of (obo:GOREL_0002004)
results_in_maintenance_of   (obo:GOREL_0012006)
lego relation (obo:LEGOREL_0000000)


Note that there are 2 GORELs in Noctua graph for which there is a RO ID: 

acts_on_population_of (obo:GOREL_0001006) RO_0012003
results_in_fusion_of (obo:GOREL_0002005)  RO_0012008
