### ISSUE TITLE
Add pathways widget and GO-CAM landing to AmiGO pages

### ISSUE THREAD

**Issue by kltm** [geneontology/project-management#66]
##### Project link
https://github.com/orgs/geneontology/projects/129

##### Project description

This project is to scoped to

- [x] the addition of the pathways widget to AmiGO
  - [x] gene product
- [x] refreshing the build and deployment of AmiGO enough to support this. 
- [x] adding a simple landing page for GO-CAM models in amigo on the /model/ path (https://github.com/geneontology/web-gocam/issues/23)

This is a follow-up to Patrick's previous work here: https://github.com/geneontology/amigo/issues/650

We will work with the POs to make the (minimal) changes to AmiGO necessary to support this (this is not meant to be a major push in AmiGO) using current technology and stack.

##### PI
Chris

##### Product owner (PO)
Seth

##### Technical lead (TL)
Seth

##### Other personnel (OP)
Patrick, Seth (, Tremayne)

##### Technical specs
N/A
All remaining work is an extension of what we currently have and review is not necessary at this time.

##### Other comments

Noting previous https://github.com/geneontology/amigo/issues/237

**Comment by kltm** [comment]
@kltm Bump start this; contact Patrick

**Comment by kltm** [comment]
@vanaukenk @ukemi , @pkalita-lbl has made some very nice progress, which is now visible at: https://amigo-staging.geneontology.io .
@cmungall Has also suggested adding the tab to term pages, which I've added to "Discussion". I think we're at the point where we (you all at least) should meet and figure out next steps.

**Comment by vanaukenk** [comment]
Neato!  Thanks @kltm and @pkalita-lbl
I just checked my favorite gene, pmk-1, which has two models.
As a quick glance, they look good, but it looks like we're using the older pathway preview rather than Tremayne's updated version?

**Comment by pkalita-lbl** [comment]
That's right, it is using a slightly older version of the widget. The latest version(s) have technical dependencies that make it incompatible with AmiGO. It's possible we could work around it in AmiGO, but it might be less effort to rework those dependencies in the widget for a future version.

**Comment by ukemi** [comment]
I just searched on one of my favorite genes Pkm Mus musculus (MGI:MGI:97591). It should at least bring back gomodel:5745387b00001516, but returns zero models.

**Comment by pkalita-lbl** [comment]
Yeah, another big caveat is that anything with an MGI ID won't work right now. The new API that backs this needs a fix so that it can resolve `MGI:MGI:xxxxx` identifiers (in addition to `MGI:xxxxx` as it currently expects).

**Comment by ukemi** [comment]
Beautiful! For now I also see the gene-centric models, but at some point we should not display those. A first step might be to use the same filtering criteria that is used other places to assign 'causal model' status. It's not ideal, but a good first step.

**Comment by pkalita-lbl** [comment]
Chris also pointed that out. I've already made the change, but it's not deployed on `amigo-staging` yet.

**Comment by pgaudet** [comment]
* Implementation of the Pathway viewer in **term** pages will be split in a different project 
* @ukemi and @vanaukenk will spec out (soon) which metadata will be shown in the models pages for the current project - which we can get to from the gene product pages

**Comment by kltm** [comment]
Rescoped; now also see https://github.com/geneontology/project-management/issues/78

**Comment by kltm** [comment]
Getting this out live will need to wait on the merged GO API hitting production: https://github.com/geneontology/project-management/issues/14

**Comment by tmushayahama** [comment]
Just to note, when LP left I was told to create a GOCAM browser landing page as a web component and it was in working but got abandoned https://github.com/geneontology/wc-web-gocam

Tagging @kltm @pkalita-lbl

**Comment by pgaudet** [comment]
Hi Pascale,

David and I can do this, but we will need input from Seth (cc'ed here) and perhaps other GO software people.

On two previous manager's calls ([8/30](https://wiki.geneontology.org/Projects_update_meeting_2023-08-30) and [9/13](https://wiki.geneontology.org/Projects_update_meeting_2023-09-13)), we noted that finishing the pathways widget project was dependent on some of the API refactor work.

Seth, let us know if you have time before Wednesday to touch base about this.  Next Monday or Tuesday would work for me; tomorrow is mostly booked.

Thanks,
--Kimberly

**Comment by kltm** [comment]
[Bringing in email thread]

---

[@pgaudet] As mentioned, as far as I'm concerned, this project has no active parts that can proceed without the production deployment of the new GO API. There is no more work here for anybody but myself and Sierra; the remaining work is probably on the order of half an hour.

While the new GO API--which is required for any further action--is /technically/ deployed, it has some data issues and may need to be withdrawn (https://github.com/geneontology/go-fastapi/issues/77; GO API project currently, but may more to general bug later today) until Sierra can take a look at it. For this reason, we have not proceeded with updating everything to point at the new pages, etc.

As there is no more functional action from Kimberly and David here, it may make the communication loop shorter and more clear if I'm put on as PO, as there are only technical considerations remaining (delta the documentation ticket for you and Suzi https://github.com/geneontology/go-site/issues/1929).

---

As an update to the email thread, it looks like we have the GO API fix in that we wanted, so I'll try wrapping up this project in the next day or so.

**Comment by pgaudet** [comment]
Hi @kltm I changed the PO and assignee to reflect your comment above.

**Comment by kltm** [comment]
@pgaudet No more active tickets here; closing out.
