### ISSUE TITLE
Relations to link MFs

### ISSUE THREAD

**Issue by kltm** [geneontology/project-management#7]
##### Project link
https://github.com/orgs/geneontology/projects/100

##### Project description

This aim of this project is to clarify use of relations to link MFs. This work may also entail creating new relations in RO. The deliverables are: a set of relations to links MFs, exemplar models and explanations, documentation, and a strategy for harmonizing existing relations with new guidelines. 

##### PI
PaulT

##### Project owner (PO)
Kimberly

##### Technical lead (TL)
Seth

##### Other personnel (OP)
David; Pascale

##### Technical specs
We will need to update Noctua to include the new MF-MF relations.  This will require work on the graph editor and the pathway editor.

##### Other comments
N/A

**Comment by pgaudet** [comment]
Managers meeting update: 

ongoing: 
- UI is done (relations are in the Noctua) 
- annotation documentation
- implement automatic replacement 
- - as part of that. we will look at the different numbers of annotations to see if it's easier to fix manually 
- this will be presented as a poster at the ISB meting

**Comment by pgaudet** [comment]
Ready to close
