### ISSUE TITLE
Clarify and improve triple store (or ditch it)

### ISSUE THREAD

**Issue by kltm** [geneontology/project-management#70]
##### Project link
https://github.com/orgs/geneontology/projects/TBD

##### Project description
Lorem ipsum

##### PI
TBD

##### Product owner (PO)
TBD

##### Technical lead (TL)
TBD

##### Other personnel (OP)
TBD

##### Technical specs
TBD (template: https://docs.google.com/document/d/111UqtS3G0aJZpAijZYI3Da0t94OQpGePlPJsqZE4Tio/edit)

##### Other comments
N/A

**Comment by pgaudet** [comment]
AI add a note on the SPARQL endpoint that this is not exactly maintained (@suzialeksander to create a go website ticket to hide the SPQARQL endpoint more)

**Comment by balhoff** [comment]
The only place I know that it is linked is on https://geneontology.cloud/home

**Comment by kltm** [comment]
https://geneontology.org/docs/sparql
https://geneontology.github.io/docs/tools-guide/

**Comment by suzialeksander** [comment]
@pgaudet there's been no action here. Should I go ahead and delete links to/mentions of sparql on the site, or do I leave the links intact with a note it's not maintained?

**Comment by pgaudet** [comment]
The request that you remove references to the SPARQL endpoint on the pages mentioned above. 

I would like @kltm to confirm since this request is more than a year old, but AFAIK this is still valid.

**Comment by kltm** [comment]
Yeah, I have some notes lying around about places to fix, but I think this can be closed as a project and reinstantiated as a docs ticket. AFAIK, we are still on the path to de-emphasizing SPARQL for public consumption, so any references found should be removed.

**Comment by pgaudet** [comment]
There is a ticket - https://github.com/geneontology/geneontology.github.io/issues/449

I will close this 'project' here.
