### ISSUE TITLE
Create merged pathways / GO-CAM widget for Alliance and GO

### ISSUE THREAD

**Issue by kltm** [geneontology/project-management#73]
##### Project link
https://github.com/orgs/geneontology/projects/140

##### Project description

The purpose of this project is to merge the "Alliance" pathway widget and the "GO" pathway widget into a single widget and codebase that is deployed at both sites.

This merged base should:

* have the most current feature base of the "Alliance" version
* have the lessened requirements of the AmiGO version (re: bootstrap)
* any skinning or toggle features to make sure there is cross-compatibility
* have any other fixes from the "AmiGO" version

##### PI
Chris

##### Product owner (PO)
Seth

##### Technical lead (TL)

Patrick

##### Other personnel (OP)

Tremayne

##### Technical specs
N/A

##### Other comments

Also see https://github.com/geneontology/amigo/issues/679

This is literally the "merging" of two used codebases, so no novelty and no technical doc needed.

**Comment by kltm** [comment]
Moving forward from discussion; tagging @pgaudet .

**Comment by kltm** [comment]
Can have initial project meeting when @pkalita-lbl is back.

**Comment by kltm** [comment]
Meeting scheduled for this Thursday.

**Comment by kltm** [comment]
In discussion, we are looking at 1-2 months. The project is essentially the tickets as currently defined.
Before we get too far along, the new GO API does need to be up.

**Comment by kltm** [comment]
@pgaudet On your approval, this should be moved to `Active`.

**Comment by kltm** [comment]
@pgaudet I'm going to go ahead and move this to `Active` to reflect the current state of things.

**Comment by pgaudet** [comment]
What's the estimated delivery date? SO I can add this to the table of Active Projects 
https://github.com/orgs/geneontology/projects/108/views/3?pane=issue&itemId=27885553

**Comment by kltm** [comment]
@pgaudet In brief communication, with current resourcing, a current estimate looks like about a month.

**Comment by kltm** [comment]
Will have meeting to see if we can wrap on Wednesday.

**Comment by kltm** [comment]
@pgaudet After talking today, we currently believe this can be wrapped before the Thanksgiving break.

**Comment by kltm** [comment]
Wrapped!
