### ISSUE TITLE
Noctua / GO-CAM working group (feedback on current curation system)

### ISSUE THREAD

**Issue by kltm** [geneontology/project-management#81]
##### Project link

https://github.com/orgs/geneontology/projects/143

##### Project description

The purpose of this project is to collect feedback from all participating groups on what needs are and are not being met with the current Noctua curation system.

##### PI

PaulT

##### Product owner (PO)

Kimberly

##### Technical lead (TL)

Seth

##### Other personnel (OP)

 David, Sierra, Tremayne, Dustin, Patrick

##### Technical specs

n/a

##### Other comments

This is a non-technical project and needs no specs.
That said, is may be useful to have @kltm in on some meetings to understand direct technical needs and provide direct feedback on technical challenges

**Comment by kltm** [comment]
@vanaukenk Seeded. I don't remember what was decide for PI.
Also tagging @pgaudet to get on her radar for when she gets back.

**Comment by kltm** [comment]
@pgaudet , advanced project state in discussion with @thomaspd and @cmungall . Waiting on resourcing.

**Comment by pgaudet** [comment]
Aim to have feedback from curators by the GO meeting

**Comment by vanaukenk** [comment]
[Initial project thoughts](https://docs.google.com/document/d/1jBvgpgT3-1NwJvLLwzwd2YCX6pt3rv4FqC8CNh5hQkQ/edit)

**Comment by pgaudet** [comment]
@vanaukenk Should this be moved at 'Active'?

**Comment by pgaudet** [comment]
Recording from 2023-11-14 meeting: https://drive.google.com/file/d/11hmN2w-yMP6EPK8NGJaFVUx2MoTJBVmt/view?usp=drive_link

**Comment by pgaudet** [comment]
High-level specs are here: https://docs.google.com/document/d/1jBvgpgT3-1NwJvLLwzwd2YCX6pt3rv4FqC8CNh5hQkQ/edit#heading=h.7bgka0z4ks6f

Some of it will implemented in the Project Noctua form refactor concealing GO-CAM model  https://github.com/geneontology/project-management/issues/87
